In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('uiuc-students-by-curriculum.csv')

/Users/ethan/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7,9,10,11,12,13,14,15,17,18,20,21,23,24,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df

,Fall,Term Code,College,Department,Degree,Major Code,Major Name,Concentration Code,Concentration Name,Total,...,All African American,All Native American,All Hawaiian/ Pac Isl,All Asian,Illinois,Non-Illinois,Academic Program Code,Legacy Advising Code,Legacy Department Code,Legacy Major Name
0,1981,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,433",...,NaN,NaN,NaN,NaN,"1,401",32,NaN,1705.0,1705.0,ACCOUNT
1,1981,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,172,...,NaN,NaN,NaN,NaN,108,64,NaN,1705.0,1705.0,ACCOUNT
2,1982,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,408",...,NaN,NaN,NaN,NaN,"1,382",26,NaN,1705.0,1705.0,ACCOUNT
3,1982,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,146,...,NaN,NaN,NaN,NaN,91,55,NaN,1705.0,1705.0,ACCOUNT
4,1983,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,392",...,NaN,NaN,NaN,NaN,"1,361",31,NaN,1705.0,1705.0,ACCOUNT
5,1983,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,137,...,NaN,NaN,NaN,NaN,81,56,NaN,1705.0,1705.0,ACCOUNT
6,2003,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,859,...,NaN,NaN,NaN,NaN,711,148,NaN,1705.0,1705.0,ACCOUNT
7,2003,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,20,...,NaN,NaN,NaN,NaN,5,15,NaN,1705.0,1705.0,ACCOUNT
8,2003,NaN,Business,NaN,NaN,NaN,Accountancy,3928,International Program,98,...,NaN,NaN,NaN,NaN,3,95,NaN,1705.0,1705.0,ACCOUNTANCY-INT
9,2003,NaN,Business,NaN,NaN,NaN,Accountancy,72,Accountancy (BS/Master Prg),84,...,NaN,NaN,NaN,NaN,67,17,NaN,1705.0,1705.0,ACCOUNTANCY-MAS
10,2003,NaN,Business,NaN,NaN,NaN,Accountancy,193,Tax,54,...,NaN,NaN,NaN,NaN,48,6,NaN,1705.0,1705.0,ACCOUNTANCY-TAX
11,2003,NaN,Business,NaN,NaN,NaN,Accountancy,73,Accountancy Postb,33,...,NaN,NaN,NaN,NaN,31,2,NaN,1705.0,1705.0,ACCY POSTBAC
12,2003,NaN,Business,NaN,NaN,NaN,Accountancy,72,Accountancy (BS/Master Prg),83,...,NaN,NaN,NaN,NaN,77,6,NaN,1705.0,1705.0,ACCY-BS/MASTER
13,1980,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,383",...,NaN,NaN,NaN,NaN,"1,362",21,NaN,1705.0,1705.0,ACCOUNT
14,1980,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,146,...,NaN,NaN,NaN,NaN,92,54,NaN,1705.0,1705.0,ACCOUNT
15,1984,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,207",...,NaN,NaN,NaN,NaN,"1,180",27,NaN,1705.0,1705.0,ACCOUNT
16,1984,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,108,...,NaN,NaN,NaN,NaN,65,43,NaN,1705.0,1705.0,ACCOUNT
17,1985,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,082",...,NaN,NaN,NaN,NaN,"1,054",28,NaN,1705.0,1705.0,ACCOUNT
18,1985,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,130,...,NaN,NaN,NaN,NaN,87,43,NaN,1705.0,1705.0,ACCOUNT
19,1986,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,942,...,NaN,NaN,NaN,NaN,915,27,NaN,1705.0,1705.0,ACCOUNT
20,1986,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,139,...,NaN,NaN,NaN,NaN,79,60,NaN,1705.0,1705.0,ACCOUNT
21,1987,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,904,...,NaN,NaN,NaN,NaN,870,34,NaN,1705.0,1705.0,ACCOUNT
22,1987,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,135,...,NaN,NaN,NaN,NaN,76,59,NaN,1705.0,1705.0,ACCOUNT
23,1988,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,019",...,NaN,NaN,NaN,NaN,972,47,NaN,1705.0,1705.0,ACCOUNT
24,1988,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,117,...,NaN,NaN,NaN,NaN,50,67,NaN,1705.0,1705.0,ACCOUNT
25,1989,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,976,...,NaN,NaN,NaN,NaN,923,53,NaN,1705.0,1705.0,ACCOUNT
26,1989,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,109,...,NaN,NaN,NaN,NaN,52,57,NaN,1705.0,1705.0,ACCOUNT
27,1990,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,087",...,NaN,NaN,NaN,NaN,"1,016",71,NaN,1705.0,1705.0,ACCOUNT
28,1990,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,93,...,NaN,NaN,NaN,NaN,39,54,NaN,1705.0,1705.0,ACCOUNT
29,1991,NaN,Business,NaN,NaN,NaN,Accountancy,NaN,NaN,"1,138",...,NaN,NaN,NaN,NaN,"1,067",71,NaN,1705.0,1705.0,ACCOUNT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17423,1984,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,13,...,NaN,NaN,NaN,NaN,13,NaN,NaN,2040.0,1560.0,VOC H E ED
17424,1985,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,17,...,NaN,NaN,NaN,NaN,17,NaN,NaN,2040.0,1560.0,VOC H E ED
17425,1986,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,15,...,NaN,NaN,NaN,NaN,15,NaN,NaN,2040.0,1560.0,VOC H E ED
17426,1987,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,11,...,NaN,NaN,NaN,NaN,11,NaN,NaN,2040.0,1560.0,VOC H E ED
17427,1988,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,6,...,NaN,NaN,NaN,NaN,5,1,NaN,2040.0,1560.0,VOC H E ED
17428,1989,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,2,...,NaN,NaN,NaN,NaN,2,NaN,NaN,2040.0,1560.0,VOC H E ED
17429,1990,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,4,...,NaN,NaN,NaN,NaN,4,NaN,NaN,2040.0,1560.0,VOC H E ED
17430,1991,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,3,...,NaN,NaN,NaN,NaN,3,NaN,NaN,2040.0,1560.0,VOC H E ED
17431,1992,NaN,ACES,NaN,NaN,NaN,VOC H E ED,NaN,NaN,2,...,NaN,NaN,NaN,NaN,2,NaN,NaN,2040.0,1560.0,VOC H E ED
17432,2018,120188.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,25,...,3.0,1,0,3.0,20,5,10KR0157BMUS,NaN,NaN,NaN
17433,2017,120178.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,34,...,5.0,0,1,2.0,26,8,10KR0157BMUS,NaN,NaN,NaN
17434,2016,120168.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,26,...,3.0,0,0,0.0,22,4,10KR0157BMUS,NaN,NaN,NaN
17435,2015,120158.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,28,...,2.0,0,1,0.0,22,6,10KR0157BMUS,NaN,NaN,NaN
17436,2014,120148.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,24,...,2.0,0,0,4.0,18,6,10KR0157BMUS,NaN,NaN,NaN
17437,2013,120138.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,26,...,2.0,0,NaN,NaN,23,3,10KR0157BMUS,NaN,NaN,NaN
17438,2012,120128.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,34,...,4.0,0,NaN,NaN,29,5,10KR0157BMUS,NaN,NaN,NaN
17439,2011,120118.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,30,...,3.0,0,NaN,NaN,25,5,10KR0157BMUS,NaN,NaN,NaN
17440,2010,120108.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,32,...,2.0,0,NaN,NaN,30,2,10KR0157BMUS,NaN,NaN,NaN
17441,2009,120098.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,30,...,NaN,NaN,NaN,NaN,30,0,10KR0157BMUS,NaN,NaN,NaN
17442,2008,120088.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,35,...,NaN,NaN,NaN,NaN,32,3,10KR0157BMUS,NaN,NaN,NaN
17443,2007,120078.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,25,...,NaN,NaN,NaN,NaN,21,4,10KR0157BMUS,NaN,NaN,NaN
17444,2006,120068.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,21,...,NaN,NaN,NaN,NaN,16,5,10KR0157BMUS,NaN,NaN,NaN
17445,2005,120058.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,19,...,NaN,NaN,NaN,NaN,14,5,10KR0157BMUS,NaN,NaN,NaN
17446,2004,120048.0,Fine and Applied Arts,495.0,BMUS,157.0,Voice,NaN,NaN,26,...,NaN,NaN,NaN,NaN,16,10,10KR0157BMUS,NaN,NaN,NaN
17447,2000,NaN,VetMed,NaN,NaN,NaN,VP SCHOLARS,NaN,NaN,2,...,NaN,NaN,NaN,NaN,0,2,NaN,4401.0,4401.0,VP SCHOLARS
17448,1980,NaN,ACES,NaN,NaN,NaN,Wood Sciences,NaN,NaN,5,...,NaN,NaN,NaN,NaN,5,NaN,NaN,1555.0,1555.0,WOOD SCI
17449,1981,NaN,ACES,NaN,NaN,NaN,Wood Sciences,NaN,NaN,5,...,NaN,NaN,NaN,NaN,5,NaN,NaN,1555.0,1555.0,WOOD SCI
17450,1982,NaN,ACES,NaN,NaN,NaN,Wood Sciences,NaN,NaN,1,...,NaN,NaN,NaN,NaN,1,NaN,NaN,1555.0,1555.0,WOOD SCI
17451,2003,NaN,Education,NaN,NaN,NaN,XMURAL,NaN,NaN,2,...,NaN,NaN,NaN,NaN,2,1,NaN,7301.0,7301.0,XMURAL
17452,1980,NaN,LAS,NaN,NaN,NaN,Zoology,NaN,NaN,3,...,NaN,NaN,NaN,NaN,2,1,NaN,3227.0,3227.0,ZOOLOGY

In [3]:
df = df[df["Major Name"].notnull()]
df = df[df["Major Name"] != "UNASSIGNED"]
df = df[df["Total"] != "Art and Design"]
null_degrees = df[df["Degree"].isnull()]
df = df[df["Degree"].notnull()]
df = df[df["Degree"].str.startswith("B")]

df = pd.concat([null_degrees, df])

In [4]:
del df["Term Code"]
del df["Department"]
del df["Degree"]
del df["Major Code"]
del df["Concentration Code"]
del df["Concentration Name"]
del df["Unknown"]
del df["Caucasian"]
del df["Asian American"]
del df["African American"]
del df["Hispanic"]
del df["Native American"]
del df["Hawaiian/Pacific Isl"]
del df["Multiracial"]
del df["International"]
del df["Unknown.1"]
del df["All African American"]
del df["All Native American"]
del df["All Hawaiian/ Pac Isl"]
del df["All Asian"]
del df["Academic Program Code"]
del df["Legacy Advising Code"]
del df["Legacy Department Code"]
del df["Legacy Major Name"]

In [5]:
def convert_str(num_str):
    try:
        return int(num_str.replace(',', '').replace(' ', ''))
    except (TypeError, AttributeError):
        return num_str

df['Total'] = df['Total'].apply(convert_str)
df['Male'] = df['Male'].apply(convert_str)
df['Female'] = df['Female'].apply(convert_str)
df['Illinois'] = df['Non-Illinois'].apply(convert_str)

In [6]:
aggregation_functions = {'Total': 'sum', 'Male': 'sum', 'Female': 'sum', 'Illinois': 'sum', 'Non-Illinois': 'sum'}
df = df.groupby(["Fall", "Major Name", "College"]).sum()

In [7]:
df.to_csv('uiuc-cleaned.csv')